apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jrpi3mg1g-nodejs
  janus-idp.io/tekton: jrpi3mg1g-nodejs
  backstage.io/kubernetes-id: jrpi3mg1g-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jrpi3mg1g-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
